### PR TITLE
Added script for generating ES UKSI lookup data files

### PR DESCRIPTION
**Pull request by burkmarr**
@johnvanbreda - this is my first stab at a script to generate the ES data files. It's a work in progress but I wanted you to see it in case it differs from what you had in mind. I've tested the generation of `taxa.yml` locally and the results look right to me. I haven't been able to test the generation of `taxon-paths.yml` because I couldn't `run prepare-taxon-paths.sql` (https://github.com/Indicia-Team/support_files/blob/master/Elasticsearch/queries/prepare-taxon-paths.sql) because the table `master_list_paths` cannot be resolved. I'm confused about that - I can't see it on the main Warehouse either.

### CODE REVIEW

**Comment by johnvanbreda** [comment]
Looks good though I'd need to follow through the sh syntax in detail to work out exactly what it's doing. 
My main question is that it will probably be easier to run this script on the Elasticsearch server so that the updated YML files can be placed directly into the location used by Logstash without intervention. Will the Elasticsearch server have access to the Warehouse PostgreSQL instance? I suspect it will but it needs checking, but the script may need modification to accept appropriate connection parameters. If not, then we might need to use the REST API to get the results back (which might be tricking in a shell script?)

**Comment by burkmarr** [comment]
Thanks John. Did you have another type of script in mind, e.g. a PHP script, rather than a shell script?

**Comment by johnvanbreda** [comment]
PHP comes to mind but only because it's keeping to the same technology as used elsewhere in Indicia. Either PHP or Python would be easy to maintain (though would ideally want to use something already available on the ES server). But if you can connect to the warehouse database across the network then the shell script should be OK?

**Comment by burkmarr** [comment]
@johnvanbreda - I've changed to a PHP script which is much better. I developed and tested this on the ES server and it appears to work well.

**Pull request merged**
